### PR TITLE
Close #273 - Define a new server property to tell HttpClient classes to use the system proxy

### LINKED ISSUE #273: ReCaptcha module proxy support
**Describe the bug**
When using the ReCaptcha module, the server has to access Google servers to validate the captcha. Unfortunately the `HttpClient` used by OpenAM is not configured to use proxy servers specified as Tomcat variables.

**To Reproduce**
1. In your enviroment, only allow access to the Internet via a proxy server
2. Set the `JAVA_OPTS` in the `setenv.sh` file as follows:
`JAVA_OPTS="$JAVAOPTS -Dhttps.proxyHost=<your_proxy_host> -Dhttps.proxyPort=<your_proxy_port> -Dhttps.nonProxyHosts=\"localhost|127.0.0.1|<whatever>\" -Dhttp.proxyHost=<your_proxy_host> -Dhttp.proxyPort=<your_proxy_port> -Dhttp.nonProxyHosts=\"localhost|127.0.0.1|<whatever>\""`
3. Configure a ReCaptcha module for login or user self service
4. Try to complete a ReCaptcha-enabled flow, you will get an Internal Server Error

**Expected behavior**
The ReCaptcha module should be able to access Google servers via the configured proxy.

**Additional context**
The fix should be easy, I will provide a pull request as soon as possible.

### PR DESCRIPTION
**Pull request by lscorcia**
This pull request adds the org.forgerock.openam.httpclienthandler.system.proxy.enabled property to let the HttpClient classes used by the User Self Service component know about JVM proxy settings.

### CODE REVIEW

File: openam-server-only/src/main/resources/config/validserverconfig.properties [hunk 1]
```diff
@@ -338,4 +338,4 @@ org.forgerock.openam.encryption.key.size=128,192,256
 org.forgerock.openam.encryption.key.digest=SHA1,SHA256,SHA384,SHA512
 org.forgerock.openam.radius.server.context.cache.size=integer
 XUI.enable=false,true
-
+org.forgerock.openam.httpclienthandler.system.proxy.enabled=false,true
```
Comment (vharseko) [inline openam-server-only/src/main/resources/config/validserverconfig.properties:341]: org.forgerock -> org.openidentityplatform

File: openam-server-only/src/main/webapp/WEB-INF/template/sms/serverdefaults.properties [hunk 2]
```diff
@@ -273,3 +273,4 @@ org.forgerock.openam.encryption.key.iterations=10000
 org.forgerock.openam.encryption.key.size=128
 org.forgerock.openam.encryption.key.digest=SHA1
 org.forgerock.openam.radius.server.context.cache.size=5000
+org.forgerock.openam.httpclienthandler.system.proxy.enabled=false
```
Comment (vharseko) [inline openam-server-only/src/main/webapp/WEB-INF/template/sms/serverdefaults.properties:276]: org.forgerock -> org.openidentityplatform

File: openam-shared/src/main/java/com/sun/identity/shared/Constants.java [hunk 3]
```diff
@@ -1384,4 +1384,9 @@
      * The name of the request attribute that tells whether this authentication happened via WS-Fed AR profile.
      */
     String WSFED_ACTIVE_LOGIN = "org.forgerock.openam.federation.wsfed.active.login";
+
+    /**
+     * Property that turns on the system http proxy for HttpClient classes.
+     */
+    public static final String SYSTEM_PROXY_ENABLED = "org.forgerock.openam.httpclienthandler.system.proxy.enabled";
```
Comment (vharseko) [inline openam-shared/src/main/java/com/sun/identity/shared/Constants.java:1391]: org.forgerock -> org.openidentityplatform

File: openam-shared/src/main/java/org/forgerock/openam/shared/guice/CloseableHttpClientHandlerProvider.java [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+     * Creates an instance of HttpClientHandler, assuring that underlying commitments are observer, i.e. listening for shutdown.
+     * @return An instance of HttpClientHandler, or an exception if an error occurred during creation.
+     */
+    @Override
+    public HttpClientHandler get() {
+        try {
+            // Enable the system proxy if the corresponding server property is set
+            Options options = Options.defaultOptions();
+            options.set(HttpClientHandler.OPTION_PROXY_SYSTEM,
+                SystemPropertiesManager.getAsBoolean(Constants.SYSTEM_PROXY_ENABLED, false));
```
Comment (vharseko) [inline openam-shared/src/main/java/org/forgerock/openam/shared/guice/CloseableHttpClientHandlerProvider.java:57]:
```
(!StringUtils.isBlank(SystemPropertiesManager.get("http.proxyHost"))||!StringUtils.isBlank(SystemPropertiesManager.get("https.proxyHost")))
```

File: openam-server-only/src/main/resources/config/validserverconfig.properties (hunk 1 above)
Comment (lscorcia) [reply openam-server-only/src/main/resources/config/validserverconfig.properties:341]: I left the org.forgerock namespace to remain compatible with the feature documentation at https://backstage.forgerock.com/docs/am/6/install-guide/#JVM-proxy-server . I can change it, but then we'll have to document this difference. What do you think?
